#Type Path                  Mode UID       GID       Age Argument
d      /var/lib/vega-web    0750 vega-web  vega-web  -
d      /etc/vega/web        0750 vega-web  vega-web  -
d      /etc/vega/web/tls    0700 vega-web  vega-web  -
